version: '3.7'

services:
  db:
    image: library/postgres:11.7-alpine
    restart: always
    container_name: db
    environment:
      POSTGRES_PASSWORD: recommendations
      POSTGRES_USER: recommendations
      POSTGRES_DB: recommendations
    volumes:
      - recommendations_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - recommendations-network
  django:
    build: .
    container_name: django
    command: >
        bash -c "python manage.py makemigrations
        && python manage.py migrate
        && python manage.py loaddata users.json
        && python manage.py load_init_data
        && python manage.py runserver 0.0.0.0:8010"
    volumes:
      - .:/recommendations
    ports:
      - 8010:8010
    depends_on:
      - db
    networks:
      - recommendations-network
networks:
  recommendations-network:

volumes:
  recommendations_data: